#Fibonacci numbers: Sum the even-valued terms of the Fibonacci sequence whose values don't exceed four million

a, b = 1, 2
x = 0

while a <= 4000000:
   if a % 2 == 0: 
      x += a
   a, b = b, a + b

print x

#Starts off as 0: 0 >> 1: 1 >> 2: 1 >> 3: 2 etc.
#Set the variable that will give us our total to 0 (x here)
#Cut off is 4 million for the a+b portion so we used a while loop
#Only adding the even-valued terms so a needs to be divisible by 2
#If it is divisible by 2, add a to the the current total while the condition is true
#Sequence is b: a + b (next number in sequence: addition of two previous numbers)
#Return the ending total (x)

'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''
